### ISSUE TITLE
Fix deployment problems

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/angular-tutorial#8]
For some reason this version doesn't deploy successfully. I thought I was just a problem with an out-of-date version of `node` in the GitHub Action for deployment, but that doesn't seem to be the case. Not sure what the problem is.

**Comment by floogulinc** [comment]
Actually it is working correctly. It's just that none of the recent commits have changed what is produced by the build so there is nothing new to commit to the `gh-pages` branch.
